## -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    module = bld.create_ns3_module('simplerouting', ['internet', 'config-store', 'tools', 'point-to-point', 'wifi', 'mobility', 'applications', 'csma'])
    module.includes = '.'
    module.source = [
        'model/simplerouting.cc',
        'helper/simplerouting-helper.cc',
        ]

    headers = bld.new_task_gen('ns3header')
    headers.module = 'simplerouting'
    headers.source = [
        'model/simplerouting.h',
        'model/simplerouting-repositories.h',
        'helper/simplerouting-helper.h',
        ]


    if bld.env['ENABLE_EXAMPLES']:
        bld.add_subdirs('examples')

    bld.ns3_python_bindings()
